//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.17 at 08:05:47 PM IST 
//


package org.wso2.carbon.identity.workflow.mgt.bean.metadata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wso2.carbon.identity.workflow.mgt.bean.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wso2.carbon.identity.workflow.mgt.bean.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParametersMetaData }
     * 
     */
    public ParametersMetaData createParametersMetaData() {
        return new ParametersMetaData();
    }

    /**
     * Create an instance of {@link ParametersMetaData.ParameterMetaData }
     * 
     */
    public ParametersMetaData.ParameterMetaData createParametersMetaDataParameterMetaData() {
        return new ParametersMetaData.ParameterMetaData();
    }

    /**
     * Create an instance of {@link ParametersMetaData.ParameterMetaData.InputData }
     * 
     */
    public ParametersMetaData.ParameterMetaData.InputData createParametersMetaDataParameterMetaDataInputData() {
        return new ParametersMetaData.ParameterMetaData.InputData();
    }

    /**
     * Create an instance of {@link ParametersMetaData.ParameterMetaData.InputData.MapType }
     * 
     */
    public ParametersMetaData.ParameterMetaData.InputData.MapType createParametersMetaDataParameterMetaDataInputDataMapType() {
        return new ParametersMetaData.ParameterMetaData.InputData.MapType();
    }

    /**
     * Create an instance of {@link ParametersMetaData.ParameterMetaData.InputData.MapType.Item }
     * 
     */
    public ParametersMetaData.ParameterMetaData.InputData.MapType.Item createParametersMetaDataParameterMetaDataInputDataMapTypeItem() {
        return new ParametersMetaData.ParameterMetaData.InputData.MapType.Item();
    }

}
