//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.23 at 06:06:20 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://metadata.bean.mgt.workflow.identity.carbon.wso2.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.wso2.carbon.identity.workflow.mgt.bean.metadata;
