//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.16 at 02:41:04 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://metadata.dto.workflow.identity.carbon.wso2.org/")
package org.wso2.carbon.identity.workflow.mgt.bean.metadata;
