//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.17 at 08:05:47 PM IST 
//


package org.wso2.carbon.identity.workflow.mgt.bean.metadata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParameterMetaData" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="RegExForValidate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InputData" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="MapType" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Item" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DataType" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}DataType" />
 *                 &lt;attribute name="InputType" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}InputType" />
 *                 &lt;attribute name="CustomInputType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Use" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}Use" default="Optional" />
 *                 &lt;attribute name="Validate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameterMetaData"
})
@XmlRootElement(name = "ParametersMetaData")
public class ParametersMetaData {

    @XmlElement(name = "ParameterMetaData", required = true)
    protected List<ParameterMetaData> parameterMetaData;

    /**
     * Gets the value of the parameterMetaData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterMetaData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterMetaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterMetaData }
     * 
     * 
     */
    public List<ParameterMetaData> getParameterMetaData() {
        if (parameterMetaData == null) {
            parameterMetaData = new ArrayList<ParameterMetaData>();
        }
        return this.parameterMetaData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="RegExForValidate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InputData" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="MapType" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Item" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DataType" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}DataType" />
     *       &lt;attribute name="InputType" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}InputType" />
     *       &lt;attribute name="CustomInputType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Use" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}Use" default="Optional" />
     *       &lt;attribute name="Validate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "displayName",
        "defaultValue",
        "regExForValidate",
        "inputData"
    })
    public static class ParameterMetaData {

        @XmlElement(name = "DisplayName", required = true)
        protected String displayName;
        @XmlElement(name = "DefaultValue")
        protected String defaultValue;
        @XmlElement(name = "RegExForValidate")
        protected String regExForValidate;
        @XmlElement(name = "InputData")
        protected InputData inputData;
        @XmlAttribute(name = "Name", required = true)
        protected String name;
        @XmlAttribute(name = "DataType")
        protected DataType dataType;
        @XmlAttribute(name = "InputType")
        protected InputType inputType;
        @XmlAttribute(name = "CustomInputType")
        protected String customInputType;
        @XmlAttribute(name = "Use")
        protected Use use;
        @XmlAttribute(name = "Validate")
        protected Boolean validate;

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Gets the value of the defaultValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultValue() {
            return defaultValue;
        }

        /**
         * Sets the value of the defaultValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultValue(String value) {
            this.defaultValue = value;
        }

        /**
         * Gets the value of the regExForValidate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegExForValidate() {
            return regExForValidate;
        }

        /**
         * Sets the value of the regExForValidate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegExForValidate(String value) {
            this.regExForValidate = value;
        }

        /**
         * Gets the value of the inputData property.
         * 
         * @return
         *     possible object is
         *     {@link InputData }
         *     
         */
        public InputData getInputData() {
            return inputData;
        }

        /**
         * Sets the value of the inputData property.
         * 
         * @param value
         *     allowed object is
         *     {@link InputData }
         *     
         */
        public void setInputData(InputData value) {
            this.inputData = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the dataType property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getDataType() {
            return dataType;
        }

        /**
         * Sets the value of the dataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setDataType(DataType value) {
            this.dataType = value;
        }

        /**
         * Gets the value of the inputType property.
         * 
         * @return
         *     possible object is
         *     {@link InputType }
         *     
         */
        public InputType getInputType() {
            return inputType;
        }

        /**
         * Sets the value of the inputType property.
         * 
         * @param value
         *     allowed object is
         *     {@link InputType }
         *     
         */
        public void setInputType(InputType value) {
            this.inputType = value;
        }

        /**
         * Gets the value of the customInputType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomInputType() {
            return customInputType;
        }

        /**
         * Sets the value of the customInputType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomInputType(String value) {
            this.customInputType = value;
        }

        /**
         * Gets the value of the use property.
         * 
         * @return
         *     possible object is
         *     {@link Use }
         *     
         */
        public Use getUse() {
            if (use == null) {
                return Use.OPTIONAL;
            } else {
                return use;
            }
        }

        /**
         * Sets the value of the use property.
         * 
         * @param value
         *     allowed object is
         *     {@link Use }
         *     
         */
        public void setUse(Use value) {
            this.use = value;
        }

        /**
         * Gets the value of the validate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isValidate() {
            if (validate == null) {
                return true;
            } else {
                return validate;
            }
        }

        /**
         * Sets the value of the validate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setValidate(Boolean value) {
            this.validate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="MapType" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Item" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mapType"
        })
        public static class InputData {

            @XmlElement(name = "MapType")
            protected MapType mapType;

            /**
             * Gets the value of the mapType property.
             * 
             * @return
             *     possible object is
             *     {@link MapType }
             *     
             */
            public MapType getMapType() {
                return mapType;
            }

            /**
             * Sets the value of the mapType property.
             * 
             * @param value
             *     allowed object is
             *     {@link MapType }
             *     
             */
            public void setMapType(MapType value) {
                this.mapType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Item" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "item"
            })
            public static class MapType {

                @XmlElement(name = "Item", required = true)
                protected List<Item> item;

                /**
                 * Gets the value of the item property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the item property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getItem().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Item }
                 * 
                 * 
                 */
                public List<Item> getItem() {
                    if (item == null) {
                        item = new ArrayList<Item>();
                    }
                    return this.item;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "key",
                    "value"
                })
                public static class Item {

                    @XmlElement(name = "Key", required = true)
                    protected String key;
                    @XmlElement(name = "Value", required = true)
                    protected String value;

                    /**
                     * Gets the value of the key property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getKey() {
                        return key;
                    }

                    /**
                     * Sets the value of the key property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setKey(String value) {
                        this.key = value;
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                }

            }

        }

    }

}
