//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.26 at 05:40:08 PM IST 
//


package org.wso2.carbon.identity.workflow.mgt.bean.metadata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParametersMetaData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParametersMetaData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParameterMetaData" type="{http://metadata.bean.mgt.workflow.identity.carbon.wso2.org}ParameterMetaData" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParametersMetaData", propOrder = {
    "parameterMetaData"
})
public class ParametersMetaData {

    @XmlElement(name = "ParameterMetaData", required = true)
    protected ParameterMetaData[] parameterMetaData;

    public ParameterMetaData[] getParameterMetaData() {
        return parameterMetaData;
    }

    public void setParameterMetaData(
            ParameterMetaData[] parameterMetaData) {
        this.parameterMetaData = parameterMetaData;
    }
}
