--Todo: This is the schema for the workflow feature. Need to move this to workflow to the feature

CREATE TABLE IF NOT EXISTS WF_REQUESTS (
    UUID VARCHAR (45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    STATUS VARCHAR (15),
    REQUEST BLOB,
    PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS WF_WS_SERVICES (
    ALIAS VARCHAR (45),
    WS_ACTION VARCHAR(255),
    SERVICE_EP VARCHAR(255),
    PRIORITY INTEGER DEFAULT 100,
    USERNAME VARCHAR(30),
    PASSWORD VARCHAR(30),
    PRIMARY KEY (ALIAS)
);

CREATE TABLE IF NOT EXISTS WF_EVENT_SERVICE_MAP (
    SERVICE_ALIAS VARCHAR(45),
    EVENT VARCHAR(45),
    CONDITION VARCHAR(1024),
    PRIMARY KEY (SERVICE_ALIAS, EVENT),
    FOREIGN KEY (SERVICE_ALIAS) REFERENCES WF_WS_SERVICES(ALIAS) ON DELETE CASCADE
);