--Todo: This is the schema for the workflow feature. Need to move it to the feature

CREATE TABLE IF NOT EXISTS WF_REQUESTS (
    UUID VARCHAR (45),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    REQUEST BLOB,
    STATUS VARCHAR (15),
    PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS WF_WS_SERVICES (
    ALIAS VARCHAR (45),
    WS_ACTION VARCHAR(100),
    SERVICE_EP VARCHAR(100),
    PRIORITY INTEGER DEFAULT 100,
    USERNAME VARCHAR(30),
    PASSWORD VARCHAR(30),
    PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS WF_REQUESTER_SERVICE_MAP (
    SERVICE_ALIAS VARCHAR(45),
    REQUESTER VARCHAR(45),
    CONDITION VARCHAR(1024),
    PRIMARY KEY (SERVICE_ALIAS, REQUESTER),
    FOREIGN KEY SERVICE_ALIAS REFERENCES WF_WS_SERVICES(ALIAS) ON DELETE CASCADE
);